# Generated by Django 6.0 on 2025-12-31 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='機関名')),
                ('organization_type', models.CharField(choices=[('MUNICIPALITY', '地方自治体'), ('POLICE_FIRE', '警察・消防'), ('GOVERNMENT', '省庁'), ('OFFICIAL_DEPS', 'その他公的機関'), ('ASSOCIATION', '協会・団体'), ('MOUNTAIN_HUT', '山小屋'), ('SNS', 'SNS/ユーザー投稿'), ('OTHER', 'その他')], default='ASSOCIATION', max_length=50, verbose_name='機関種別')),
                ('prefecture_code', models.CharField(default='13', max_length=2, verbose_name='都道府県コード')),
                ('url', models.URLField(blank=True, verbose_name='公式URL')),
                ('data_format', models.CharField(choices=[('WEB', 'Webページ')], default='WEB', max_length=50, verbose_name='データ形式')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='最終確認日時')),
            ],
            options={
                'verbose_name': '情報源',
                'verbose_name_plural': '情報源',
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='登山道名/区間名')),
                ('mountain', models.CharField(max_length=20, verbose_name='山名')),
                ('area', models.CharField(choices=[('OKUTAMA', '奥多摩'), ('TANZAWA', '丹沢'), ('TAKAO', '高尾・奥高尾'), ('HAKONE', '箱根'), ('OKUMUSASHI', '奥武蔵'), ('OKUCHICHIBU', '奥秩父'), ('DAIBOSATSU', '大菩薩連嶺')], default='OKUTAMA', max_length=20, verbose_name='山域')),
                ('location_description', models.TextField(blank=True, verbose_name='位置説明')),
                ('prefecture_code', models.CharField(blank=True, default='13', max_length=2, null=True, verbose_name='都道府県コード')),
                ('municipality', models.CharField(blank=True, max_length=5, null=True, verbose_name='市区町村コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail_status.datasource', verbose_name='情報源')),
            ],
            options={
                'verbose_name': '登山道',
                'verbose_name_plural': '登山道',
            },
        ),
        migrations.CreateModel(
            name='TrailCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLOSURE', '🚧 通行止め・閉鎖'), ('HAZARD', '⚠️ 危険箇所・通行注意'), ('SNOW', '❄️ 積雪・アイスバーン'), ('ANIMAL', '🐻 動物出没'), ('WEATHER', '🌧️ 気象警報'), ('FACILITY', '🏠 施設情報'), ('WATER', '💧 水場状況'), ('OTHER', '📝 その他')], default='CLOSURE', max_length=20, verbose_name='状況種別')),
                ('severity', models.CharField(choices=[('EMERGENCY', '緊急'), ('WARNING', '警告'), ('CAUTION', '注意'), ('INFO', '情報')], default='INFO', max_length=10, verbose_name='重要度')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('location_detail', models.CharField(blank=True, max_length=300, verbose_name='詳細位置')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='報告日時')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='有効開始')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有効期限')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail_status.datasource', verbose_name='情報源')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='trail_status.trail', verbose_name='登山道')),
            ],
            options={
                'verbose_name': '状況情報',
                'verbose_name_plural': '状況情報',
                'ordering': ['-reported_at', '-severity'],
            },
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['prefecture_code', 'municipality'], name='trail_statu_prefect_086e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['area'], name='trail_statu_area_ddcf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['mountain'], name='trail_statu_mountai_dc7897_idx'),
        ),
        migrations.AddIndex(
            model_name='trailcondition',
            index=models.Index(fields=['trail', 'status'], name='trail_statu_trail_i_3013a1_idx'),
        ),
        migrations.AddIndex(
            model_name='trailcondition',
            index=models.Index(fields=['status', 'severity'], name='trail_statu_status_e7c166_idx'),
        ),
        migrations.AddIndex(
            model_name='trailcondition',
            index=models.Index(fields=['valid_until', 'is_active'], name='trail_statu_valid_u_0f792b_idx'),
        ),
    ]
