# Generated by Django 6.0 on 2026-01-04 06:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='機関名')),
                ('organization_type', models.CharField(choices=[('MUNICIPALITY', '地方自治体'), ('POLICE_FIRE', '警察・消防'), ('GOVERNMENT', '省庁'), ('OFFICIAL_DEPS', 'その他公的機関'), ('ASSOCIATION', '協会・団体'), ('MOUNTAIN_HUT', '山小屋'), ('SNS', 'SNS/ユーザー投稿'), ('OTHER', 'その他')], default='ASSOCIATION', max_length=50, verbose_name='機関種別')),
                ('prefecture_code', models.CharField(blank=True, default='13', max_length=2, verbose_name='都道府県コード')),
                ('prompt_key', models.CharField(help_text='例: okutama_vc, kumotori_hut', max_length=50, unique=True, verbose_name='プロンプトキー')),
                ('url1', models.URLField(max_length=500, verbose_name='URL①')),
                ('url2', models.URLField(blank=True, max_length=500, verbose_name='URL②')),
                ('data_format', models.CharField(choices=[('WEB', 'Webページ')], default='WEB', max_length=50, verbose_name='データ形式')),
                ('content_hash', models.CharField(blank=True, help_text='スクレイピング内容のハッシュ値（変更検知用）', max_length=64, verbose_name='コンテンツハッシュ')),
                ('last_scraped_at', models.DateTimeField(blank=True, help_text='最後にコンテンツを取得した日時', null=True, verbose_name='最終スクレイピング日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '情報源',
                'verbose_name_plural': '情報源',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MountainGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='山名')),
                ('area', models.CharField(choices=[('OKUTAMA', '奥多摩'), ('TANZAWA', '丹沢'), ('TAKAO', '高尾・奥高尾'), ('HAKONE', '箱根'), ('OKUMUSASHI', '奥武蔵'), ('OKUCHICHIBU', '奥秩父'), ('DAIBOSATSU', '大菩薩連嶺')], max_length=20, verbose_name='山域')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)], verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(160)], verbose_name='経度')),
            ],
            options={
                'verbose_name': '山グループ',
                'verbose_name_plural': '山グループ',
                'indexes': [models.Index(fields=['name'], name='trail_statu_name_f3a76c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MountainAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=50, unique=True, verbose_name='別名・マイナー山名')),
                ('mountain_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='trail_status.mountaingroup', verbose_name='山グループ')),
            ],
            options={
                'verbose_name': '山名別名',
                'verbose_name_plural': '山名別名',
            },
        ),
        migrations.CreateModel(
            name='PromptBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, help_text='例: 001_okutama_vc.yaml', max_length=100, verbose_name='ファイル名')),
                ('content', models.TextField(verbose_name='プロンプト内容')),
                ('backup_date', models.DateTimeField(auto_now_add=True, verbose_name='バックアップ日時')),
                ('file_hash', models.CharField(help_text='SHA256ハッシュ', max_length=64, unique=True, verbose_name='ファイルハッシュ')),
                ('file_size', models.IntegerField(default=0, verbose_name='ファイルサイズ(bytes)')),
                ('backup_type', models.CharField(choices=[('scheduled', '定期'), ('manual', '手動'), ('emergency', '緊急')], default='scheduled', max_length=20, verbose_name='バックアップ種別')),
            ],
            options={
                'verbose_name': 'プロンプトバックアップ',
                'verbose_name_plural': 'プロンプトバックアップ',
                'ordering': ['-backup_date'],
                'indexes': [models.Index(fields=['file_name', '-backup_date'], name='trail_statu_file_na_e9a0f7_idx'), models.Index(fields=['backup_type', '-backup_date'], name='trail_statu_backup__936a21_idx')],
            },
        ),
        migrations.CreateModel(
            name='LlmUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='LLMモデル')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='入力トークン数')),
                ('thinking_tokens', models.IntegerField(default=0, verbose_name='思考トークン数')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='出力トークン数')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='コスト(USD)')),
                ('conditions_extracted', models.IntegerField(default=0, verbose_name='抽出された状況数')),
                ('success', models.BooleanField(default=True, verbose_name='処理成功')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('execution_time_seconds', models.FloatField(blank=True, null=True, verbose_name='実行時間(秒)')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail_status.datasource', verbose_name='情報源')),
            ],
            options={
                'verbose_name': 'LLM利用履歴',
                'verbose_name_plural': 'LLM利用履歴',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['executed_at', 'model'], name='trail_statu_execute_3a6570_idx'), models.Index(fields=['source', '-executed_at'], name='trail_statu_source__906411_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrailCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.URLField(verbose_name='情報源URL')),
                ('trail_name', models.CharField(max_length=50, verbose_name='登山道名・区間（原文）')),
                ('mountain_name_raw', models.CharField(blank=True, default='', max_length=50, verbose_name='山名（原文）')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル（原文）')),
                ('description', models.TextField(blank=True, verbose_name='詳細説明（原文）')),
                ('reported_at', models.DateField(blank=True, default=None, null=True, verbose_name='報告日')),
                ('resolved_at', models.DateField(blank=True, default=None, help_text='既存の該当項目の登山道状況の問題が解消された場合、あるいは解消される日時が判明した場合にのみ入力', null=True, verbose_name='解消日')),
                ('status', models.CharField(choices=[('CLOSURE', '🚧 通行止め・閉鎖'), ('HAZARD', '⚠️ 危険箇所・通行注意'), ('SNOW', '❄️ 積雪・アイスバーン'), ('ANIMAL', '🐻 動物出没'), ('WEATHER', '🌧️ 気象警報'), ('FACILITY', '🏠 施設情報'), ('WATER', '💧 水場状況'), ('OTHER', '📝 その他')], default='CLOSURE', max_length=20, verbose_name='状況種別')),
                ('area', models.CharField(choices=[('OKUTAMA', '奥多摩'), ('TANZAWA', '丹沢'), ('TAKAO', '高尾・奥高尾'), ('HAKONE', '箱根'), ('OKUMUSASHI', '奥武蔵'), ('OKUCHICHIBU', '奥秩父'), ('DAIBOSATSU', '大菩薩連嶺')], max_length=20, verbose_name='山域')),
                ('reference_URL', models.URLField(blank=True, max_length=500, verbose_name='補足URL（pdf等）')),
                ('comment', models.TextField(blank=True, verbose_name='備考欄')),
                ('ai_model', models.CharField(blank=True, help_text='例: deepseek-reasoner', max_length=50, verbose_name='使用AIモデル')),
                ('prompt_file', models.CharField(blank=True, help_text='例: 001_okutama_vc.yaml', max_length=100, verbose_name='プロンプトファイル')),
                ('ai_config', models.JSONField(blank=True, help_text='temperature, thinking_budgetなどの設定', null=True, verbose_name='AI設定')),
                ('disabled', models.BooleanField(default=False, help_text='[使用例] 誤情報だった場合ほか', verbose_name='情報の無効化（管理用）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('mountain_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trail_status.mountaingroup', verbose_name='山グループ')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trail_status.datasource', verbose_name='情報源')),
            ],
            options={
                'verbose_name': '登山道状態',
                'verbose_name_plural': '登山道状態',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['disabled', 'resolved_at', '-reported_at'], name='trail_statu_disable_a2fffa_idx'), models.Index(fields=['area', 'status', 'disabled', '-reported_at'], name='trail_statu_area_9859a9_idx'), models.Index(fields=['mountain_name_raw', 'trail_name', '-reported_at'], name='trail_statu_mountai_51c54b_idx')],
            },
        ),
    ]
