# Generated by Django 6.0 on 2026-01-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailcondition',
            name='comment',
            field=models.TextField(blank=True, verbose_name='備考欄'),
        ),
        migrations.AddField(
            model_name='trailcondition',
            name='reference_URL',
            field=models.URLField(blank=True, verbose_name='補足URL（pdf等）'),
        ),
        migrations.AlterField(
            model_name='trailcondition',
            name='disabled',
            field=models.BooleanField(default=False, help_text='[使用例] 誤情報だった場合ほか', verbose_name='情報の無効化（管理用）'),
        ),
    ]
