# Generated by Django 6.0 on 2026-01-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0002_trailcondition_comment_trailcondition_reference_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='url1',
            field=models.URLField(max_length=500, verbose_name='URL①'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url2',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL②'),
        ),
        migrations.AlterField(
            model_name='trailcondition',
            name='reference_URL',
            field=models.URLField(blank=True, max_length=500, verbose_name='補足URL（pdf等）'),
        ),
    ]
