# Generated by Django 6.0 on 2026-01-02 15:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0003_alter_datasource_url1_alter_datasource_url2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['id'], 'verbose_name': '情報源', 'verbose_name_plural': '情報源'},
        ),
        migrations.CreateModel(
            name='LlmUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='LLMモデル')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='入力トークン数')),
                ('thinking_tokens', models.IntegerField(default=0, verbose_name='思考トークン数')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='出力トークン数')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='コスト(USD)')),
                ('conditions_extracted', models.IntegerField(default=0, verbose_name='抽出された状況数')),
                ('success', models.BooleanField(default=True, verbose_name='処理成功')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('execution_time_seconds', models.FloatField(blank=True, null=True, verbose_name='実行時間(秒)')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail_status.datasource', verbose_name='情報源')),
            ],
            options={
                'verbose_name': 'LLM利用履歴',
                'verbose_name_plural': 'LLM利用履歴',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['executed_at', 'model'], name='trail_statu_execute_3a6570_idx'), models.Index(fields=['source', '-executed_at'], name='trail_statu_source__906411_idx')],
            },
        ),
    ]
