# Generated by Django 6.0 on 2026-01-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0004_alter_datasource_options_llmusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='prompt_key',
            field=models.CharField(default='okutama_vc', help_text='例: okutama_vc, mitake_vc', max_length=50, verbose_name='プロンプトキー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailcondition',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trail_status.datasource', verbose_name='情報源'),
        ),
    ]
