# Generated by Django 6.0 on 2026-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0005_datasource_prompt_key_alter_trailcondition_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='prompt_key',
            field=models.CharField(help_text='例: okutama_vc, kumotori_hut', max_length=50, unique=True, verbose_name='プロンプトキー'),
        ),
    ]
