# Generated by Django 6.0 on 2026-01-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0006_alter_datasource_prompt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailcondition',
            name='ai_config',
            field=models.JSONField(blank=True, help_text='temperature, thinking_budgetなどの設定', null=True, verbose_name='AI設定'),
        ),
        migrations.AddField(
            model_name='trailcondition',
            name='ai_model',
            field=models.CharField(blank=True, help_text='例: deepseek-reasoner', max_length=50, verbose_name='使用AIモデル'),
        ),
        migrations.AddField(
            model_name='trailcondition',
            name='prompt_file',
            field=models.CharField(blank=True, help_text='例: 001_okutama_vc.yaml', max_length=100, verbose_name='プロンプトファイル'),
        ),
        migrations.CreateModel(
            name='PromptBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, help_text='例: 001_okutama_vc.yaml', max_length=100, verbose_name='ファイル名')),
                ('content', models.TextField(verbose_name='プロンプト内容')),
                ('backup_date', models.DateTimeField(auto_now_add=True, verbose_name='バックアップ日時')),
                ('file_hash', models.CharField(help_text='SHA256ハッシュ', max_length=64, unique=True, verbose_name='ファイルハッシュ')),
                ('file_size', models.IntegerField(default=0, verbose_name='ファイルサイズ(bytes)')),
                ('backup_type', models.CharField(choices=[('scheduled', '定期'), ('manual', '手動'), ('emergency', '緊急')], default='scheduled', max_length=20, verbose_name='バックアップ種別')),
            ],
            options={
                'verbose_name': 'プロンプトバックアップ',
                'verbose_name_plural': 'プロンプトバックアップ',
                'ordering': ['-backup_date'],
                'indexes': [models.Index(fields=['file_name', '-backup_date'], name='trail_statu_file_na_e9a0f7_idx'), models.Index(fields=['backup_type', '-backup_date'], name='trail_statu_backup__936a21_idx')],
            },
        ),
    ]
